name: CD Droid Apk 

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    permissions:
        contents: write
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore workload
      run: dotnet workload restore 
    - name: Restore dependencies
      run: dotnet restore
    - name: Build Release
      run: dotnet build Maui/ChronoTimer.Maui.csproj -c Release -f net8.0-android --no-restore
    - name: Release
      uses: softprops/action-gh-release@v2.0.8
      with:
        files: ./**/Release/**/*-Signed.apk
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
